[package]
name = "coach"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
thiserror = "2.0.20"
clap = { version = "4.6.6", features = ["derive"] }
ctrlc = "3.5.2"
futures = "0.3.34"
async-trait = "0.1.92"
qdrant-client = "1.19.0"
rand = "0.10.2"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"
log = "0.4.33"
env_logger = "0.11.11"
hdrhistogram = "7.6.0"

[lints]
workspace = true

[workspace.lints.clippy]
cast_lossless = "warn"
doc_link_with_quotes = "warn"
enum_glob_use = "warn"
explicit_into_iter_loop = "warn"
filter_map_next = "warn"
flat_map_option = "warn"
implicit_clone = "warn"
inconsistent_struct_constructor = "warn"
inefficient_to_string = "warn"
manual_is_variant_and = "warn"
manual_let_else = "warn"
needless_continue = "warn"
needless_raw_string_hashes = "warn"
ptr_as_ptr = "warn"
ref_option_ref = "warn"
uninlined_format_args = "warn"
unnecessary_wraps = "warn"
unused_self = "warn"
used_underscore_binding = "warn"
match_wildcard_for_single_variants = "warn"
needless_pass_by_ref_mut = "warn"
unused_async = "warn"
wildcard_enum_match_arm = "warn"

[profile.release]
lto = "fat"
codegen-units = 1
